# Generated by Django 2.0.3 on 2018-12-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
