# Generated by Django 2.0.3 on 2018-12-04 07:59

import collections
from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_auto_20181204_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='vat',
            new_name='vat_no',
        ),
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default='11B Muller Street South', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(default='Joe Plumber', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='street_address',
            field=models.CharField(default='18B Muller Street North', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billed_items',
            field=jsonfield.fields.JSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
