# Generated by Django 2.0.3 on 2018-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_auto_20181204_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoiced',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street_address',
            field=models.CharField(max_length=32),
        ),
    ]
