# Generated by Django 2.0.3 on 2018-12-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_processor', '0002_item_cost'),
        ('invoicing', '0005_auto_20181204_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed', to='document_processor.Billed'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billed_to', to='document_processor.Profile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoiced',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
